### ISSUE TITLE
camera test

### ISSUE THREAD

**Issue by mugginsjm** [AndreaFavero71/CUBOTino_micro#2]
I'm working through this and now on section "PiCamera focus"

(.virtualenvs) pi@rubicPI:~/cubotino_micro/src $ python Cubotino_m_servos.py --picamera_test

usage: Cubotino_m_servos.py [-h] [--set SET] [--tune] [--fast]
Cubotino_m_servos.py: error: unrecognized arguments: --picamera_test
(.virtualenvs) pi@rubicPI:~/cubotino_micro/src $

**Comment by AndreaFavero71** [comment]
I'm now traveling.
On top of mind that argument is associated to Cubotino_m.py

**Comment by AndreaFavero71** [comment]
Cubotino_m_servos.py has two arguments (set, tune);  The argument picamera_test was wrongly associated to the Cubotino_m_servos.py at the instructions.

The argument --picamera_test works on Cubotino_T.py
